### ISSUE TITLE
fwupd not appearing in flathub.org

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.freedesktop.fwupd#3]
Flathub.org (the website) gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml

This app is not appearing in the website because it has some issues in the appstream information:

    * `<component type="generic"> `should be `<component type="desktop">` or `<component type="console-application">`

Well, actually console-application is not supported yet. I just asked @TingPing  about this yesterday
https://github.com/flathub/io.gitlab.sdl_jstest.sdl_jstest/issues/1

**Comment by hughsie** [comment]
I guess `console-application` is closer than `generic`. I'll make this change upstream now, and we'll pick it up for the next release. Do we also need an icon to show up in flathub.org?

**Comment by jgarciao** [comment]
This are the fist console-applications and there are no rules yet. I would
prefer if you could provide an icon (64x64 and 128x128)

Please note that the webapp backend currently ignores all components that
are not desktop-applications so, it won't be published until I fix it


El dv., 15 de febr. 2019, 10:14, Richard Hughes <notifications@github.com>
va escriure:

**Comment by hughsie** [comment]
SVG icon provided: https://github.com/hughsie/fwupd/commit/97293c456027e7c0625621940cbae8ac25d03506

**Comment by TingPing** [comment]
I don't think CLI tools should show up on flathub.org, they don't show up in G-S right @hughsie ?

**Comment by hughsie** [comment]
> they don't show up in G-S right

Yes, they do. More by accident I think.

**Comment by jgarciao** [comment]
I'm sorry but I think svg icons are not currently supported. You'll find more info and example build manifests where they use the tool rsvg-convert to create them here:
https://github.com/flathub/org.gnome.Weather/issues/2#issuecomment-456026946

@TingPing In my opinion, once the cli apps are in the repo they should be easy discoverable (so they should be in flathub.org and g-s) and easy launchable (they should appear, with an, in gnome-shell apps)

**Comment by TingPing** [comment]
> and easy launchable (they should appear, with an, in gnome-shell apps)

CLI apps are by definition not launchable. They are singular commands that do a thing and then exit.

Again I'm separating that from TUI applications that are long running interactable console apps.

**Comment by hughsie** [comment]
Okay, 64x64 and 128x128 icons generated. Thanks for all the tips. Fingers crossed it'll show up soon.
